// app/layout.tsx

import { Metadata } from "next";
import RootLayout1 from "../components/RootLayout";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <ToastContainer />
      <RootLayout1>{children}</RootLayout1>
    </>
  );
}
